# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sd/sqbin-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sd/sqbin-common/proprietary/bin/avahi-daemon:system/bin/avahi-daemon \
    vendor/sd/sqbin-common/proprietary/bin/bdt:system/bin/bdt \
    vendor/sd/sqbin-common/proprietary/bin/bugmailer.sh:system/bin/bugmailer.sh \
    vendor/sd/sqbin-common/proprietary/bin/charger:system/bin/charger \
    vendor/sd/sqbin-common/proprietary/bin/chat:system/bin/chat \
    vendor/sd/sqbin-common/proprietary/bin/crda:system/bin/crda \
    vendor/sd/sqbin-common/proprietary/bin/cryptomem:system/bin/cryptomem \
    vendor/sd/sqbin-common/proprietary/bin/eject:system/bin/eject \
    vendor/sd/sqbin-common/proprietary/bin/init-pppd.sh:system/bin/init-pppd.sh \
    vendor/sd/sqbin-common/proprietary/bin/load-modules.sh:system/bin/load-modules.sh \
    vendor/sd/sqbin-common/proprietary/bin/mkntfs:system/bin/mkntfs \
    vendor/sd/sqbin-common/proprietary/bin/navd:system/bin/navd \
    vendor/sd/sqbin-common/proprietary/bin/ntfsck:system/bin/ntfsck \
    vendor/sd/sqbin-common/proprietary/bin/rild:system/bin/rild \
    vendor/sd/sqbin-common/proprietary/bin/send_bug:system/bin/send_bug \
    vendor/sd/sqbin-common/proprietary/bin/setbcb:system/bin/setbcb \
    vendor/sd/sqbin-common/proprietary/bin/usb_modeswitch:system/bin/usb_modeswitch \
    vendor/sd/sqbin-common/proprietary/bin/wifical.sh:system/bin/wifical.sh \
    vendor/sd/sqbin-common/proprietary/etc/avahi-daemon.conf:system/etc/avahi-daemon.conf \
    vendor/sd/sqbin-common/proprietary/etc/spn-conf.xml:system/etc/spn-conf.xml \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fmc_ch8_1283.2.bts:system/etc/firmware/fmc_ch8_1283.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fmc_ch8_1853.3.bts:system/etc/firmware/fmc_ch8_1853.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fmc_ch8_1893.2.bts:system/etc/firmware/fmc_ch8_1893.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fmc_ch8_1893.3.bts:system/etc/firmware/fmc_ch8_1893.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_rx_ch8_1283.2.bts:system/etc/firmware/fm_rx_ch8_1283.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_rx_ch8_1853.3.bts:system/etc/firmware/fm_rx_ch8_1853.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_rx_ch8_1893.2.bts:system/etc/firmware/fm_rx_ch8_1893.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_rx_ch8_1893.3.bts:system/etc/firmware/fm_rx_ch8_1893.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1273.1.bts:system/etc/firmware/fm_tx_ch8_1273.1.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1273.2.bts:system/etc/firmware/fm_tx_ch8_1273.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1283.2.bts:system/etc/firmware/fm_tx_ch8_1283.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1853.3.bts:system/etc/firmware/fm_tx_ch8_1853.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1893.2.bts:system/etc/firmware/fm_tx_ch8_1893.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_ch8_1893.3.bts:system/etc/firmware/fm_tx_ch8_1893.3.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_11.7.27.bts:system/etc/firmware/TIInit_11.7.27.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_11.8.32.bts:system/etc/firmware/TIInit_11.8.32.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_12.7.27.bts:system/etc/firmware/TIInit_12.7.27.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TIInit_12.8.32.bts:system/etc/firmware/TIInit_12.8.32.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TINfcInit_12.8.32.72.bts:system/etc/firmware/TINfcInit_12.8.32.72.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/TINfcInit_12.8.32.80.bts:system/etc/firmware/TINfcInit_12.8.32.80.bts \
    vendor/sd/sqbin-common/proprietary/etc/firmware/ti-connectivity/wl128x-fw-4-mr.bin:system/etc/firmware/ti-connectivity/wl128x-fw-4-mr.bin \
    vendor/sd/sqbin-common/proprietary/etc/firmware/ti-connectivity/wl128x-fw-4-plt.bin:system/etc/firmware/ti-connectivity/wl128x-fw-4-plt.bin \
    vendor/sd/sqbin-common/proprietary/etc/firmware/ti-connectivity/wl128x-fw-4-sr.bin:system/etc/firmware/ti-connectivity/wl128x-fw-4-sr.bin \
    vendor/sd/sqbin-common/proprietary/etc/firmware/ti-connectivity/wl1271-nvs.bin:system/etc/firmware/ti-connectivity/wl1271-nvs.bin \
    vendor/sd/sqbin-common/proprietary/etc/wifi/RFMD_S_3.5.ini:system/etc/wifi/RFMD_S_3.5.ini \
    vendor/sd/sqbin-common/proprietary/etc/wifi/TQS_S_2.6.ini:system/etc/wifi/TQS_S_2.6.ini \
    vendor/sd/sqbin-common/proprietary/lib/libexfat.so:system/lib/libexfat.so \
    vendor/sd/sqbin-common/proprietary/lib/libfmradio.so:system/lib/libfmradio.so \
    vendor/sd/sqbin-common/proprietary/lib/libft2.so:system/lib/libft2.so \
    vendor/sd/sqbin-common/proprietary/lib/libfuse.so:system/lib/libfuse.so \
    vendor/sd/sqbin-common/proprietary/lib/libgps.so:system/lib/libgps.so \
    vendor/sd/sqbin-common/proprietary/lib/libgpsservices.so:system/lib/libgpsservices.so \
    vendor/sd/sqbin-common/proprietary/lib/libhhtech-ril.so:system/lib/libhhtech-ril.so \
    vendor/sd/sqbin-common/proprietary/lib/libmcphalgps.so:system/lib/libmcphalgps.so \
    vendor/sd/sqbin-common/proprietary/lib/libntfs-3g.so:system/lib/libntfs-3g.so \
    vendor/sd/sqbin-common/proprietary/lib/libpng.so:system/lib/libpng.so \
    vendor/sd/sqbin-common/proprietary/lib/libsupllocationprovider.so:system/lib/libsupllocationprovider.so \
    vendor/sd/sqbin-common/proprietary/lib/libusb.so:system/lib/libusb.so \
    vendor/sd/sqbin-common/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/sd/sqbin-common/proprietary/lib/crda/regulatory.bin:system/lib/crda/regulatory.bin \
    vendor/sd/sqbin-common/proprietary/lib/drm/libfwdlockengine.so:system/lib/drm/libfwdlockengine.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/audio.hdmi.omap4.so:system/lib/hw/audio.hdmi.omap4.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/audio.primary.omap4.so:system/lib/hw/audio.primary.omap4.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/camera.omap4.so:system/lib/hw/camera.omap4.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/gps.omap4.so:system/lib/hw/gps.omap4.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/lights.panda.so:system/lib/hw/lights.panda.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/power.panda.so:system/lib/hw/power.panda.so \
    vendor/sd/sqbin-common/proprietary/lib/hw/sensors.panda.so:system/lib/hw/sensors.panda.so \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_0.png:system/usr/share/charger/battery_0.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_1.png:system/usr/share/charger/battery_1.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_2.png:system/usr/share/charger/battery_2.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_3.png:system/usr/share/charger/battery_3.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_4.png:system/usr/share/charger/battery_4.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_5.png:system/usr/share/charger/battery_5.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_charge.png:system/usr/share/charger/battery_charge.png \
    vendor/sd/sqbin-common/proprietary/usr/share/charger/battery_fail.png:system/usr/share/charger/battery_fail.png

# vendor/sd/sqbin-common/proprietary/lib/libion_ti.so:system/lib/libion_ti.so \
# vendor/sd/sqbin-common/proprietary/lib/libedid.so:system/lib/libedid.so \
# vendor/sd/sqbin-common/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
