# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sd/sqsgx-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sd/sqsgx-common/proprietary/etc/powervr.ini:/system/etc/powervr.ini \
    vendor/sd/sqsgx-common/proprietary/lib/egl/egl.cfg:/system/lib/egl/egl.cfg \
    vendor/sd/sqsgx-common/proprietary/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/sd/sqsgx-common/proprietary/vendor/bin/pvrsrvinit:/system/vendor/bin/pvrsrvinit \
    vendor/sd/sqsgx-common/proprietary/vendor/bin/pvrsrvctl_SGX540_120:/system/vendor/bin/pvrsrvctl_SGX540_120 \
    vendor/sd/sqsgx-common/proprietary/vendor/bin/pvrsrvctl_SGX544_112:/system/vendor/bin/pvrsrvctl_SGX544_112 \
    vendor/sd/sqsgx-common/proprietary/vendor/firmware/ducati-m3.bin:/system/vendor/firmware/ducati-m3.bin \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libbltsville_gc2d.2.2.0.0.so:/system/vendor/lib/libbltsville_gc2d.2.2.0.0.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libbltsville_ticpu.2.1.0.0.so:/system/vendor/lib/libbltsville_ticpu.2.1.0.0.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libbltsville_ticpu_license.txt:/system/vendor/lib/libbltsville_ticpu_license.txt \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libbt-vendor.so:/system/vendor/lib/libbt-vendor.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libglslcompiler_SGX540_120.so:/system/vendor/lib/libglslcompiler_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libglslcompiler_SGX544_112.so:/system/vendor/lib/libglslcompiler_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libIMGegl_SGX540_120.so:/system/vendor/lib/libIMGegl_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libIMGegl_SGX544_112.so:/system/vendor/lib/libIMGegl_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libpvr2d_SGX540_120.so:/system/vendor/lib/libpvr2d_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libpvr2d_SGX544_112.so:/system/vendor/lib/libpvr2d_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:/system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so:/system/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libPVRScopeServices_SGX540_120.so:/system/vendor/lib/libPVRScopeServices_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libPVRScopeServices_SGX544_112.so:/system/vendor/lib/libPVRScopeServices_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libsrv_init_SGX540_120.so:/system/vendor/lib/libsrv_init_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libsrv_init_SGX544_112.so:/system/vendor/lib/libsrv_init_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libsrv_um_SGX540_120.so:/system/vendor/lib/libsrv_um_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libsrv_um_SGX544_112.so:/system/vendor/lib/libsrv_um_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libusc_SGX540_120.so:/system/vendor/lib/libusc_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/libusc_SGX544_112.so:/system/vendor/lib/libusc_SGX544_112.so \    
#   vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so:/system/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so:/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so:/system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/hw/gralloc.omap4430.so:/system/vendor/lib/hw/gralloc.omap4430.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/hw/gralloc.omap4470.so:/system/vendor/lib/hw/gralloc.omap4470.so \
    vendor/sd/sqsgx-common/proprietary/vendor/lib/hw/hwcomposer.omap4.so:/system/vendor/lib/hw/hwcomposer.omap4.so
    